In [4]:
import pandas as pd

df = pd.read_csv('world.csv')
df

,ID,iso_code,洲名,國家,日期,總確診數,新增確診數,七天移動平均新增確診數,總死亡數,新增死亡數,...,七天移動平均疫苗新增接種劑數,每百人接種疫苗劑數,每百人接種疫苗人數,疫情控管指數,總人口數,中位數年紀,70歲以上人口比例,平均壽命,解除隔離數,解封指數
0,1,AFG,亞洲,阿富汗,2020-02-24,5,5,0.000,0,0,...,0.0,0.00,0.00,8.33,39835428,18.6,1.337,64.83,0,99999.0
1,2,AFG,亞洲,阿富汗,2020-02-25,5,0,0.000,0,0,...,0.0,0.00,0.00,8.33,39835428,18.6,1.337,64.83,0,99999.0
2,3,AFG,亞洲,阿富汗,2020-02-26,5,0,0.000,0,0,...,0.0,0.00,0.00,8.33,39835428,18.6,1.337,64.83,0,99999.0
3,4,AFG,亞洲,阿富汗,2020-02-27,5,0,0.000,0,0,...,0.0,0.00,0.00,8.33,39835428,18.6,1.337,64.83,0,99999.0
4,5,AFG,亞洲,阿富汗,2020-02-28,5,0,0.000,0,0,...,0.0,0.00,0.00,8.33,39835428,18.6,1.337,64.83,0,99999.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
187880,187881,ZWE,非洲,辛巴威,2022-07-02,255586,0,39.571,5555,0,...,6190.0,79.41,41.81,0.00,15092171,19.6,1.882,61.49,0,99999.0
187881,187882,ZWE,非洲,辛巴威,2022-07-03,255586,0,33.000,5555,0,...,8710.0,79.55,41.86,0.00,15092171,19.6,1.882,61.49,0,99999.0
187882,187883,ZWE,非洲,辛巴威,2022-07-04,255726,140,49.000,5558,3,...,10797.0,79.67,41.90,0.00,15092171,19.6,1.882,61.49,0,99999.0
187883,187884,ZWE,非洲,辛巴威,2022-07-05,255755,29,53.143,5558,0,...,10821.0,79.68,41.90,0.00,15092171,19.6,1.882,61.49,0,99999.0
187884,187885,ZWE,非洲,辛巴威,2022-07-06,255805,50,40.714,5560,2,...,0.0,0.00,0.00,0.00,15092171,19.6,1.882,61.49,0,99999.0

In [7]:
df1=df.query('國家 == "台灣"')
df1

,ID,iso_code,洲名,國家,日期,總確診數,新增確診數,七天移動平均新增確診數,總死亡數,新增死亡數,...,七天移動平均疫苗新增接種劑數,每百人接種疫苗劑數,每百人接種疫苗人數,疫情控管指數,總人口數,中位數年紀,70歲以上人口比例,平均壽命,解除隔離數,解封指數
163986,163987,TWN,亞洲,台灣,2020-01-16,0,0,0.000,0,0,...,0.0,0.00,0.00,8.33,23855008,42.2,8.353,80.46,0,99999.00
163987,163988,TWN,亞洲,台灣,2020-01-17,0,0,0.000,0,0,...,0.0,0.00,0.00,8.33,23855008,42.2,8.353,80.46,0,99999.00
163988,163989,TWN,亞洲,台灣,2020-01-18,0,0,0.000,0,0,...,0.0,0.00,0.00,8.33,23855008,42.2,8.353,80.46,0,99999.00
163989,163990,TWN,亞洲,台灣,2020-01-19,0,0,0.000,0,0,...,0.0,0.00,0.00,8.33,23855008,42.2,8.353,80.46,0,99999.00
163990,163991,TWN,亞洲,台灣,2020-01-20,0,0,0.000,0,0,...,0.0,0.00,0.00,13.89,23855008,42.2,8.353,80.46,0,99999.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
164884,164885,TWN,亞洲,台灣,2022-07-02,3837856,34807,37736.143,6868,96,...,85345.0,0.00,0.00,0.00,23855008,42.2,8.353,80.46,14835,258.17
164885,164886,TWN,亞洲,台灣,2022-07-03,3870528,32672,36740.429,6956,88,...,83512.0,243.72,88.80,0.00,23855008,42.2,8.353,80.46,14835,260.37
164886,164887,TWN,亞洲,台灣,2022-07-04,3893643,23115,35960.286,7025,69,...,80397.0,244.04,88.81,0.00,23855008,42.2,8.353,80.46,14835,261.94
164887,164888,TWN,亞洲,台灣,2022-07-05,3929627,35984,34755.571,7128,103,...,79776.0,244.41,88.82,0.00,23855008,42.2,8.353,80.46,14835,264.37
164888,164889,TWN,亞洲,台灣,2022-07-06,3964188,34561,33689.286,7223,95,...,75670.0,244.76,88.83,0.00,23855008,42.2,8.353,80.46,14835,266.71

In [10]:
df2 = df1.sort_values(by='新增確診數',ascending=False)
df2.head(5)

,ID,iso_code,洲名,國家,日期,總確診數,新增確診數,七天移動平均新增確診數,總死亡數,新增死亡數,...,七天移動平均疫苗新增接種劑數,每百人接種疫苗劑數,每百人接種疫苗人數,疫情控管指數,總人口數,中位數年紀,70歲以上人口比例,平均壽命,解除隔離數,解封指數
164835,164836,TWN,亞洲,台灣,2022-05-14,699824,128954,61607.857,1049,81,...,76312.0,0.00,0.00,26.85,23855008,42.2,8.353,80.46,14835,46.24
164830,164831,TWN,亞洲,台灣,2022-05-09,397504,128935,37792.714,931,35,...,87600.0,223.06,83.27,26.85,23855008,42.2,8.353,80.46,14835,25.86
164848,164849,TWN,亞洲,台灣,2022-05-27,1735067,94796,82682.286,1784,126,...,83406.0,229.17,85.45,26.85,23855008,42.2,8.353,80.46,14835,116.08
164840,164841,TWN,亞洲,台灣,2022-05-19,1070561,89420,71384.429,1235,59,...,75623.0,226.26,84.29,26.85,23855008,42.2,8.353,80.46,14835,71.25
164846,164847,TWN,亞洲,台灣,2022-05-25,1558380,89361,82462.714,1554,76,...,71461.0,228.02,84.85,26.85,23855008,42.2,8.353,80.46,14835,104.15

In [15]:
df3=df2.set_index('日期')
df3

,ID,iso_code,洲名,國家,總確診數,新增確診數,七天移動平均新增確診數,總死亡數,新增死亡數,七天移動平均新增死亡數,...,七天移動平均疫苗新增接種劑數,每百人接種疫苗劑數,每百人接種疫苗人數,疫情控管指數,總人口數,中位數年紀,70歲以上人口比例,平均壽命,解除隔離數,解封指數
日期,,,,,,,,,,,,,,,,,,,,,
2022-05-14,164836,TWN,亞洲,台灣,699824,128954,61607.857,1049,81,21.857,...,76312.0,0.00,0.00,26.85,23855008,42.2,8.353,80.46,14835,46.24
2022-05-09,164831,TWN,亞洲,台灣,397504,128935,37792.714,931,35,9.000,...,87600.0,223.06,83.27,26.85,23855008,42.2,8.353,80.46,14835,25.86
2022-05-27,164849,TWN,亞洲,台灣,1735067,94796,82682.286,1784,126,71.429,...,83406.0,229.17,85.45,26.85,23855008,42.2,8.353,80.46,14835,116.08
2022-05-19,164841,TWN,亞洲,台灣,1070561,89420,71384.429,1235,59,38.143,...,75623.0,226.26,84.29,26.85,23855008,42.2,8.353,80.46,14835,71.25
2022-05-25,164847,TWN,亞洲,台灣,1558380,89361,82462.714,1554,76,54.000,...,71461.0,228.02,84.85,26.85,23855008,42.2,8.353,80.46,14835,104.15
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-02-15,164017,TWN,亞洲,台灣,18,0,0.143,0,0,0.000,...,0.0,0.00,0.00,30.56,23855008,42.2,8.353,80.46,2,99999.00
2020-02-18,164020,TWN,亞洲,台灣,22,0,0.571,1,0,0.000,...,0.0,0.00,0.00,30.56,23855008,42.2,8.353,80.46,2,10.52
2020-01-18,163989,TWN,亞洲,台灣,0,0,0.000,0,0,0.000,...,0.0,0.00,0.00,8.33,23855008,42.2,8.353,80.46,0,99999.00
2020-01-17,163988,TWN,亞洲,台灣,0,0,0.000,0,0,0.000,...,0.0,0.00,0.00,8.33,23855008,42.2,8.353,80.46,0,99999.00
2020-01-16,163987,TWN,亞洲,台灣,0,0,0.000,0,0,0.000,...,0.0,0.00,0.00,8.33,23855008,42.2,8.353,80.46,0,99999.00

In [20]:
df3['no_rank'] = df3['新增確診數'].rank(method='first',ascending=False).astype(int)
df3

,ID,iso_code,洲名,國家,總確診數,新增確診數,七天移動平均新增確診數,總死亡數,新增死亡數,七天移動平均新增死亡數,...,每百人接種疫苗劑數,每百人接種疫苗人數,疫情控管指數,總人口數,中位數年紀,70歲以上人口比例,平均壽命,解除隔離數,解封指數,no_rank
日期,,,,,,,,,,,,,,,,,,,,,
2022-05-14,164836,TWN,亞洲,台灣,699824,128954,61607.857,1049,81,21.857,...,0.00,0.00,26.85,23855008,42.2,8.353,80.46,14835,46.24,1
2022-05-09,164831,TWN,亞洲,台灣,397504,128935,37792.714,931,35,9.000,...,223.06,83.27,26.85,23855008,42.2,8.353,80.46,14835,25.86,2
2022-05-27,164849,TWN,亞洲,台灣,1735067,94796,82682.286,1784,126,71.429,...,229.17,85.45,26.85,23855008,42.2,8.353,80.46,14835,116.08,3
2022-05-19,164841,TWN,亞洲,台灣,1070561,89420,71384.429,1235,59,38.143,...,226.26,84.29,26.85,23855008,42.2,8.353,80.46,14835,71.25,4
2022-05-25,164847,TWN,亞洲,台灣,1558380,89361,82462.714,1554,76,54.000,...,228.02,84.85,26.85,23855008,42.2,8.353,80.46,14835,104.15,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-02-15,164017,TWN,亞洲,台灣,18,0,0.143,0,0,0.000,...,0.00,0.00,30.56,23855008,42.2,8.353,80.46,2,99999.00,899
2020-02-18,164020,TWN,亞洲,台灣,22,0,0.571,1,0,0.000,...,0.00,0.00,30.56,23855008,42.2,8.353,80.46,2,10.52,900
2020-01-18,163989,TWN,亞洲,台灣,0,0,0.000,0,0,0.000,...,0.00,0.00,8.33,23855008,42.2,8.353,80.46,0,99999.00,901
2020-01-17,163988,TWN,亞洲,台灣,0,0,0.000,0,0,0.000,...,0.00,0.00,8.33,23855008,42.2,8.353,80.46,0,99999.00,902
2020-01-16,163987,TWN,亞洲,台灣,0,0,0.000,0,0,0.000,...,0.00,0.00,8.33,23855008,42.2,8.353,80.46,0,99999.00,903

In [18]:
df3.head()

,ID,iso_code,洲名,國家,總確診數,新增確診數,七天移動平均新增確診數,總死亡數,新增死亡數,七天移動平均新增死亡數,...,每百人接種疫苗劑數,每百人接種疫苗人數,疫情控管指數,總人口數,中位數年紀,70歲以上人口比例,平均壽命,解除隔離數,解封指數,no_rank
日期,,,,,,,,,,,,,,,,,,,,,
2022-05-14,164836,TWN,亞洲,台灣,699824,128954,61607.857,1049,81,21.857,...,0.00,0.00,26.85,23855008,42.2,8.353,80.46,14835,46.24,903
2022-05-09,164831,TWN,亞洲,台灣,397504,128935,37792.714,931,35,9.000,...,223.06,83.27,26.85,23855008,42.2,8.353,80.46,14835,25.86,902
2022-05-27,164849,TWN,亞洲,台灣,1735067,94796,82682.286,1784,126,71.429,...,229.17,85.45,26.85,23855008,42.2,8.353,80.46,14835,116.08,901
2022-05-19,164841,TWN,亞洲,台灣,1070561,89420,71384.429,1235,59,38.143,...,226.26,84.29,26.85,23855008,42.2,8.353,80.46,14835,71.25,900
2022-05-25,164847,TWN,亞洲,台灣,1558380,89361,82462.714,1554,76,54.000,...,228.02,84.85,26.85,23855008,42.2,8.353,80.46,14835,104.15,899