In [1]:
import numpy as np
np.linspace(-3,3)

array([-3.        , -2.87755102, -2.75510204, -2.63265306, -2.51020408,
       -2.3877551 , -2.26530612, -2.14285714, -2.02040816, -1.89795918,
       -1.7755102 , -1.65306122, -1.53061224, -1.40816327, -1.28571429,
       -1.16326531, -1.04081633, -0.91836735, -0.79591837, -0.67346939,
       -0.55102041, -0.42857143, -0.30612245, -0.18367347, -0.06122449,
        0.06122449,  0.18367347,  0.30612245,  0.42857143,  0.55102041,
        0.67346939,  0.79591837,  0.91836735,  1.04081633,  1.16326531,
        1.28571429,  1.40816327,  1.53061224,  1.65306122,  1.7755102 ,
        1.89795918,  2.02040816,  2.14285714,  2.26530612,  2.3877551 ,
        2.51020408,  2.63265306,  2.75510204,  2.87755102,  3.        ])

In [2]:
array = np.linspace(-3,3,num=100)
array * 10

array([-30.        , -29.39393939, -28.78787879, -28.18181818,
       -27.57575758, -26.96969697, -26.36363636, -25.75757576,
       -25.15151515, -24.54545455, -23.93939394, -23.33333333,
       -22.72727273, -22.12121212, -21.51515152, -20.90909091,
       -20.3030303 , -19.6969697 , -19.09090909, -18.48484848,
       -17.87878788, -17.27272727, -16.66666667, -16.06060606,
       -15.45454545, -14.84848485, -14.24242424, -13.63636364,
       -13.03030303, -12.42424242, -11.81818182, -11.21212121,
       -10.60606061, -10.        ,  -9.39393939,  -8.78787879,
        -8.18181818,  -7.57575758,  -6.96969697,  -6.36363636,
        -5.75757576,  -5.15151515,  -4.54545455,  -3.93939394,
        -3.33333333,  -2.72727273,  -2.12121212,  -1.51515152,
        -0.90909091,  -0.3030303 ,   0.3030303 ,   0.90909091,
         1.51515152,   2.12121212,   2.72727273,   3.33333333,
         3.93939394,   4.54545455,   5.15151515,   5.75757576,
         6.36363636,   6.96969697,   7.57575758,   8.18181818,
         8.78787879,   9.39393939,  10.        ,  10.60606061,
        11.21212121,  11.81818182,  12.42424242,  13.03030303,
        13.63636364,  14.24242424,  14.84848485,  15.45454545,
        16.06060606,  16.66666667,  17.27272727,  17.87878788,
        18.48484848,  19.09090909,  19.6969697 ,  20.3030303 ,
        20.90909091,  21.51515152,  22.12121212,  22.72727273,
        23.33333333,  23.93939394,  24.54545455,  25.15151515,
        25.75757576,  26.36363636,  26.96969697,  27.57575758,
        28.18181818,  28.78787879,  29.39393939,  30.        ])

In [3]:
np.random.randint(50,size=100,high=101)

array([ 73,  87,  50,  84,  80,  81,  72,  66,  69,  78,  59,  61,  64,
        50,  64,  54,  56,  50,  59,  77,  51,  54, 100,  55,  86,  56,
        81,  67,  55,  95,  89,  55,  64,  72,  88,  98,  79,  81,  51,
        94,  58,  94,  97, 100,  69,  96,  87,  90,  63,  69,  90,  53,
        86,  51,  91,  58,  79,  50, 100,  56,  62,  88,  90,  70,  95,
        71,  66,  70,  97,  98,  75,  82,  90,  99,  90,  69,  94,  62,
        81,  71,  60,  77,  77,  72,  59,  80,  98,  86,  78,  53,  70,
        71,  68,  68,  62,  84,  92,  78,  88,  63])

In [4]:
content = np.random.randint(50,size=(50,5),high=101)

In [5]:
import pandas as pd
df1 = pd.DataFrame(data=content,
             index=[f"第{i}號"for i in range(1,51)],
             columns=['國文','英文','數學','地理','歷史'])
df1

       國文  英文  數學   地理   歷史
第1號    83  70  75   63   71
第2號    94  52  80   76   54
第3號    94  77  58   65   83
第4號    57  66  54   64   68
第5號    89  73  86   50   54
第6號    83  98  57   80   54
第7號    74  87  69   79   82
第8號    77  65  62   61   73
第9號    86  71  67   91   62
第10號   62  55  74   62   73
第11號   67  79  73   74   83
第12號   60  89  65   68   62
第13號   80  50  81   70   54
第14號   79  79  61   81   61
第15號   73  81  60   59   68
第16號   54  50  74   67   97
第17號   81  74  81   93   91
第18號   54  87  86   96   74
第19號   88  61  99   50   74
第20號   52  87  82   90   78
第21號   97  98  79   91   54
第22號   96  89  98   95   63
第23號   59  71  62   79   92
第24號   64  53  85   85   90
第25號   92  99  66   96   86
第26號   53  57  80   90   99
第27號   62  83  99   78   53
第28號   89  68  77   91   52
第29號   88  81  53   57   68
第30號   79  50  52   53   84
第31號   75  69  98   59   71
第32號   94  55  61   56   87
第33號   59  87  57   58   60
第34號   80  82  76   90   64
第35號   56  94  73   53   94
第36號   74  51  89   65   68
第37號   75  59  79   61   52
第38號   84  74  84   54   95
第39號   75  97  60   85   55
第40號  100  89  56  100   83
第41號   71  81  56   76   55
第42號   58  62  67   98   96
第43號   77  59  62   82   51
第44號   67  88  50   77   62
第45號   91  79  86   74   86
第46號   62  56  63   93   57
第47號   89  88  60   60   91
第48號   82  76  86   85  100
第49號   92  94  58   87   74
第50號   71  83  64   62   63

In [6]:
df1.loc["第1號",:]

國文    83
英文    70
數學    75
地理    63
歷史    71
Name: 第1號, dtype: int64

In [7]:
df1.loc["第1號"]

國文    83
英文    70
數學    75
地理    63
歷史    71
Name: 第1號, dtype: int64

In [8]:
df1.loc[["第1號","第5號","第10號"]]

      國文  英文  數學  地理  歷史
第1號   83  70  75  63  71
第5號   89  73  86  50  54
第10號  62  55  74  62  73

In [9]:
df1.iloc[:5]

     國文  英文  數學  地理  歷史
第1號  83  70  75  63  71
第2號  94  52  80  76  54
第3號  94  77  58  65  83
第4號  57  66  54  64  68
第5號  89  73  86  50  54

In [10]:
df1.iloc[-5:]

      國文  英文  數學  地理   歷史
第46號  62  56  63  93   57
第47號  89  88  60  60   91
第48號  82  76  86  85  100
第49號  92  94  58  87   74
第50號  71  83  64  62   63

In [11]:
df1.loc['第10號':'第15號']

      國文  英文  數學  地理  歷史
第10號  62  55  74  62  73
第11號  67  79  73  74  83
第12號  60  89  65  68  62
第13號  80  50  81  70  54
第14號  79  79  61  81  61
第15號  73  81  60  59  68

In [12]:
student_sum = df1.sum(axis=1)
student_mean = df1.mean(axis=1)
df1['總分'] = student_sum
df1['平均'] = student_mean
df1

       國文  英文  數學   地理   歷史   總分    平均
第1號    83  70  75   63   71  362  72.4
第2號    94  52  80   76   54  356  71.2
第3號    94  77  58   65   83  377  75.4
第4號    57  66  54   64   68  309  61.8
第5號    89  73  86   50   54  352  70.4
第6號    83  98  57   80   54  372  74.4
第7號    74  87  69   79   82  391  78.2
第8號    77  65  62   61   73  338  67.6
第9號    86  71  67   91   62  377  75.4
第10號   62  55  74   62   73  326  65.2
第11號   67  79  73   74   83  376  75.2
第12號   60  89  65   68   62  344  68.8
第13號   80  50  81   70   54  335  67.0
第14號   79  79  61   81   61  361  72.2
第15號   73  81  60   59   68  341  68.2
第16號   54  50  74   67   97  342  68.4
第17號   81  74  81   93   91  420  84.0
第18號   54  87  86   96   74  397  79.4
第19號   88  61  99   50   74  372  74.4
第20號   52  87  82   90   78  389  77.8
第21號   97  98  79   91   54  419  83.8
第22號   96  89  98   95   63  441  88.2
第23號   59  71  62   79   92  363  72.6
第24號   64  53  85   85   90  377  75.4
第25號   92  99  66   96   86  439  87.8
第26號   53  57  80   90   99  379  75.8
第27號   62  83  99   78   53  375  75.0
第28號   89  68  77   91   52  377  75.4
第29號   88  81  53   57   68  347  69.4
第30號   79  50  52   53   84  318  63.6
第31號   75  69  98   59   71  372  74.4
第32號   94  55  61   56   87  353  70.6
第33號   59  87  57   58   60  321  64.2
第34號   80  82  76   90   64  392  78.4
第35號   56  94  73   53   94  370  74.0
第36號   74  51  89   65   68  347  69.4
第37號   75  59  79   61   52  326  65.2
第38號   84  74  84   54   95  391  78.2
第39號   75  97  60   85   55  372  74.4
第40號  100  89  56  100   83  428  85.6
第41號   71  81  56   76   55  339  67.8
第42號   58  62  67   98   96  381  76.2
第43號   77  59  62   82   51  331  66.2
第44號   67  88  50   77   62  344  68.8
第45號   91  79  86   74   86  416  83.2
第46號   62  56  63   93   57  331  66.2
第47號   89  88  60   60   91  388  77.6
第48號   82  76  86   85  100  429  85.8
第49號   92  94  58   87   74  405  81.0
第50號   71  83  64   62   63  343  68.6